"""Disassemble SPC700 code, so the APU can be looked at as well as heard.

The emulator has had an SPC700 for a long time and no way to read what it is
running, which is fine until a game stops talking to its own sound driver --
and then it is the only thing that matters.  Rudra no Hihou is that game.

The opcode table is transcribed mechanically from bsnes's SPC700
disassembler rather than typed out here: 256 entries written from memory is
exactly the kind of thing this project has been bitten by before.  The
mnemonics are bsnes's, which are 65816-flavoured -- `lda $12` for what other
assemblers write `mov a,$12`, `jsr` for `call`, `jst` for `tcall`, and
`bne --$12=$34` for `dbnz` -- and they are kept as they came rather than
renamed, for the same reason.

    from tools.spcdisasm import disassemble
    text, length = disassemble(lambda a: ram[a], 0x0CF5)
"""

# (template, length in bytes) indexed by opcode.
TABLE = [
    ('nop', 1),
    ('jst $ffde', 1),
    ('set ${dp0}:0', 2),
    ('bbs ${dp0}:0=${rel3_1}', 3),
    ('ora ${dp0}', 2),
    ('ora ${abs}', 3),
    ('ora (x)', 1),
    ('ora (${dp0},x)', 2),
    ('ora #${imm0}', 2),
    ('orr ${dp1}=${dp0}', 3),
    ('orc ${absbit}', 3),
    ('asl ${dp0}', 2),
    ('asl ${abs}', 3),
    ('php', 1),
    ('tsb ${abs}', 3),
    ('brk', 1),
    ('bpl ${rel2_0}', 2),
    ('jst $ffdc', 1),
    ('clr ${dp0}:0', 2),
    ('bbc ${dp0}:0=${rel3_1}', 3),
    ('ora ${dp0},x', 2),
    ('ora ${abs},x', 3),
    ('ora ${abs},y', 3),
    ('ora (${dp0}),y', 2),
    ('orr ${dp1}=#${imm0}', 3),
    ('orr (x)=(y)', 1),
    ('dew ${dp0}', 2),
    ('asl ${dp0},x', 2),
    ('asl', 1),
    ('dex', 1),
    ('cpx ${abs}', 3),
    ('jmp (${abs},x)', 3),
    ('clp', 1),
    ('jst $ffda', 1),
    ('set ${dp0}:1', 2),
    ('bbs ${dp0}:1=${rel3_1}', 3),
    ('and ${dp0}', 2),
    ('and ${abs}', 3),
    ('and (x)', 1),
    ('and (${dp0},x)', 2),
    ('and #${imm0}', 2),
    ('and ${dp1}=${dp0}', 3),
    ('orc !${absbit}', 3),
    ('rol ${dp0}', 2),
    ('rol ${abs}', 3),
    ('pha', 1),
    ('bne ${dp0}=${rel3_1}', 3),
    ('bra ${rel2_0}', 2),
    ('bmi ${rel2_0}', 2),
    ('jst $ffd8', 1),
    ('clr ${dp0}:1', 2),
    ('bbc ${dp0}:1=${rel3_1}', 3),
    ('and ${dp0},x', 2),
    ('and ${abs},x', 3),
    ('and ${abs},y', 3),
    ('and (${dp0}),y', 2),
    ('and ${dp1}=#${imm0}', 3),
    ('and (x)=(y)', 1),
    ('inw ${dp0}', 2),
    ('rol ${dp0},x', 2),
    ('rol', 1),
    ('inx', 1),
    ('cpx ${dp0}', 2),
    ('jsr ${abs}', 3),
    ('sep', 1),
    ('jst $ffd6', 1),
    ('set ${dp0}:2', 2),
    ('bbs ${dp0}:2=${rel3_1}', 3),
    ('eor ${dp0}', 2),
    ('eor ${abs}', 3),
    ('eor (x)', 1),
    ('eor (${dp0},x)', 2),
    ('eor #${imm0}', 2),
    ('eor ${dp1}=${dp0}', 3),
    ('and ${absbit}', 3),
    ('lsr ${dp0}', 2),
    ('lsr ${abs}', 3),
    ('phx', 1),
    ('trb ${abs}', 3),
    ('jsp $ff{imm0}', 2),
    ('bvc ${rel2_0}', 2),
    ('jst $ffd4', 1),
    ('clr ${dp0}:2', 2),
    ('bbc ${dp0}:2=${rel3_1}', 3),
    ('eor ${dp0},x', 2),
    ('eor ${abs},x', 3),
    ('eor ${abs},y', 3),
    ('eor (${dp0}),y', 2),
    ('eor ${dp1}=#${imm0}', 3),
    ('eor (x)=(y)', 1),
    ('cpw ${abs}', 3),
    ('lsr ${dp0},x', 2),
    ('lsr', 1),
    ('tax', 1),
    ('cpy ${abs}', 3),
    ('jmp ${abs}', 3),
    ('clc', 1),
    ('jst $ffd2', 1),
    ('set ${dp0}:3', 2),
    ('bbs ${dp0}:3=${rel3_1}', 3),
    ('cmp ${dp0}', 2),
    ('cmp ${abs}', 3),
    ('cmp (x)', 1),
    ('cmp (${dp0},x)', 2),
    ('cmp #${imm0}', 2),
    ('cmp ${dp1}=${dp0}', 3),
    ('and !${absbit}', 3),
    ('ror ${dp0}', 2),
    ('ror ${abs}', 3),
    ('phy', 1),
    ('bne --${dp0}=${rel3_1}', 3),
    ('rts', 1),
    ('bvs ${rel2_0}', 2),
    ('jst $ffd0', 1),
    ('clr ${dp0}:3', 2),
    ('bbc ${dp0}:3=${rel3_1}', 3),
    ('cmp ${dp0},x', 2),
    ('cmp ${abs},x', 3),
    ('cmp ${abs},y', 3),
    ('cmp (${dp0}),y', 2),
    ('cmp ${dp1}=#${imm0}', 3),
    ('cmp (x)=(y)', 1),
    ('adw ${abs}', 3),
    ('ror ${dp0},x', 2),
    ('ror', 1),
    ('txa', 1),
    ('cpy ${dp0}', 2),
    ('rti', 1),
    ('sec', 1),
    ('jst $ffce', 1),
    ('set ${dp0}:4', 2),
    ('bbs ${dp0}:4=${rel3_1}', 3),
    ('adc ${dp0}', 2),
    ('adc ${abs}', 3),
    ('adc (x)', 1),
    ('adc (${dp0},x)', 2),
    ('adc #${imm0}', 2),
    ('adc ${dp1}=${dp0}', 3),
    ('eor ${absbit}', 3),
    ('dec ${dp0}', 2),
    ('dec ${abs}', 3),
    ('ldy #${imm0}', 2),
    ('plp', 1),
    ('str ${dp1}=#${imm0}', 3),
    ('bcc ${rel2_0}', 2),
    ('jst $ffcc', 1),
    ('clr ${dp0}:4', 2),
    ('bbc ${dp0}:4=${rel3_1}', 3),
    ('adc ${dp0},x', 2),
    ('adc ${abs},x', 3),
    ('adc ${abs},y', 3),
    ('adc (${dp0}),y', 2),
    ('adc ${dp1}=#${imm0}', 3),
    ('adc (x)=(y)', 1),
    ('sbw ${abs}', 3),
    ('dec ${dp0},x', 2),
    ('dec', 1),
    ('tsx', 1),
    ('div', 1),
    ('xcn', 1),
    ('sei', 1),
    ('jst $ffca', 1),
    ('set ${dp0}:5', 2),
    ('bbs ${dp0}:5=${rel3_1}', 3),
    ('sbc ${dp0}', 2),
    ('sbc ${abs}', 3),
    ('sbc (x)', 1),
    ('sbc (${dp0},x)', 2),
    ('sbc #${imm0}', 2),
    ('sbc ${dp1}=${dp0}', 3),
    ('ldc ${absbit}', 3),
    ('inc ${dp0}', 2),
    ('inc ${abs}', 3),
    ('cpy #${imm0}', 2),
    ('pla', 1),
    ('sta (x++)', 1),
    ('bcs ${rel2_0}', 2),
    ('jst $ffc8', 1),
    ('clr ${dp0}:5', 2),
    ('bbc ${dp0}:5=${rel3_1}', 3),
    ('sbc ${dp0},x', 2),
    ('sbc ${abs},x', 3),
    ('sbc ${abs},y', 3),
    ('sbc (${dp0}),y', 2),
    ('sbc ${dp1}=#${imm0}', 3),
    ('sbc (x)=(y)', 1),
    ('ldw ${dp0}', 2),
    ('inc ${dp0},x', 2),
    ('inc', 1),
    ('txs', 1),
    ('das', 1),
    ('lda (x++)', 1),
    ('cli', 1),
    ('jst $ffc6', 1),
    ('set ${dp0}:6', 2),
    ('bbs ${dp0}:6=${rel3_1}', 3),
    ('sta ${dp0}', 2),
    ('sta ${abs}', 3),
    ('sta (x)', 1),
    ('sta (${dp0},x)', 2),
    ('cpx #${imm0}', 2),
    ('stx ${abs}', 3),
    ('stc ${absbit}', 3),
    ('sty ${dp0}', 2),
    ('sty ${abs}', 3),
    ('ldx #${imm0}', 2),
    ('plx', 1),
    ('mul', 1),
    ('bne ${rel2_0}', 2),
    ('jst $ffc4', 1),
    ('clr ${dp0}:6', 2),
    ('bbc ${dp0}:6=${rel3_1}', 3),
    ('sta ${dp0},x', 2),
    ('sta ${abs},x', 3),
    ('sta ${abs},y', 3),
    ('sta (${dp0}),y', 2),
    ('stx ${dp0}', 2),
    ('stx ${dp0},y', 2),
    ('stw ${dp0}', 2),
    ('sty ${dp0},x', 2),
    ('dey', 1),
    ('tya', 1),
    ('bne ${dp0},x=${rel3_1}', 3),
    ('daa', 1),
    ('clv', 1),
    ('jst $ffc2', 1),
    ('set ${dp0}:7', 2),
    ('bbs ${dp0}:7=${rel3_1}', 3),
    ('lda ${dp0}', 2),
    ('lda ${abs}', 3),
    ('lda (x)', 1),
    ('lda (${dp0},x)', 2),
    ('lda #${imm0}', 2),
    ('ldx ${abs}', 3),
    ('not ${absbit}', 3),
    ('ldy ${dp0}', 2),
    ('ldy ${abs}', 3),
    ('cmc', 1),
    ('ply', 1),
    ('wai', 1),
    ('beq ${rel2_0}', 2),
    ('jst $ffc0', 1),
    ('clr ${dp0}:7', 2),
    ('bbc ${dp0}:7=${rel3_1}', 3),
    ('lda ${dp0},x', 2),
    ('lda ${abs},x', 3),
    ('lda ${abs},y', 3),
    ('lda (${dp0}),y', 2),
    ('ldx ${dp0}', 2),
    ('ldx ${dp0},y', 2),
    ('str ${dp1}=${dp0}', 3),
    ('ldy ${dp0},x', 2),
    ('iny', 1),
    ('tay', 1),
    ('bne --y=${rel2_0}', 2),
    ('stp', 1),
]


def disassemble(read, addr, p=0):
    """Return (text, length) for the instruction at `addr`.

    `read` takes an address and returns a byte.  `p` is the direct-page flag
    from PSW: with it set the direct page is $0100 rather than $0000, which
    changes what a direct-page operand means and so is part of the text.
    """
    op = read(addr) & 0xFF
    template, length = TABLE[op]

    def byte(n):
        return read((addr + 1 + n) & 0xFFFF) & 0xFF

    fields = {}
    for n in (0, 1):
        fields["dp%d" % n] = "%03X" % ((p << 8) + byte(n))
        fields["imm%d" % n] = "%02X" % byte(n)
    word = byte(0) | (byte(1) << 8)
    fields["abs"] = "%04X" % word
    fields["absbit"] = "%04X:%X" % (word & 0x1FFF, word >> 13)
    for r in (2, 3):
        for n in (0, 1):
            off = byte(n)
            if off > 127:
                off -= 256
            fields["rel%d_%d" % (r, n)] = "%04X" % ((addr + r + off) & 0xFFFF)
    return template.format(**fields), length


def disassemble_range(read, addr, count, p=0):
    out = []
    for _ in range(count):
        text, length = disassemble(read, addr, p)
        raw = " ".join("%02X" % (read((addr + i) & 0xFFFF) & 0xFF) for i in range(length))
        out.append("%04X  %-9s %s" % (addr, raw, text))
        addr = (addr + length) & 0xFFFF
    return out
